load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "module_repos_lib",
    srcs = [
        "attrs.go",
        "main.go",
        "repositories.go",
        "targets.go",
    ],
    importpath = "github.com/EngFlow/gazelle_cc/index/module_repos",
    visibility = ["//visibility:private"],
    deps = [
        "//index/internal/bazel",
        "//index/internal/bazel/proto",
        "//index/internal/indexer",
        "//index/internal/indexer/cli",
        "//internal/collections",
        "//internal/index",
        "@gazelle//label",
    ],
)

go_binary(
    name = "module_repos",
    embed = [":module_repos_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "module_repos_test",
    srcs = ["targets_test.go"],
    embed = [":module_repos_lib"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@gazelle//label",
    ],
)
